In [1]:
%matplotlib inline
import numpy as np
from IPython.core.display import HTML
HTML('<link href="https://fonts.googleapis.com/css?family=Cabin|Quicksand" rel="stylesheet"><style>.container{width:90% !important; font-family: "Cabin", sans-serif;}em{color: red !important;}</style><style>.output_png {display: table-cell;text-align: center;vertical-align: middle;}</style>')

# Coordinate system

- given basis ${v_1, v_2, ..., v_n}$ of $V$ 
- we can construct a *coordinate* system for $V$: 
<br>the vector $v$ with coordinates $(a_1, a_2, ..., a_n)$ is the linear combination
$$v = a_{1}v_{1}+a_{2}v_{2}+\cdots +a_{n}v_{n}$$

- because ${v_1, v_2, ..., v_n}$ span $V$ $\rightarrow$ *any*  $v \in V$ can be assigned coordinates
- because ${v_1, v_2, ..., v_n}$ are linearly independent $\rightarrow$ the coordinates are *unique*
<br>i.e. there is only *one* linear combination that is equal to $v$

# Coordinate system

- once a basis of a vector space $V$ has been *chosen*
- a vector $V$ may be *identified* with n coordinates in ${\rm I\!R}^n$
- vector operations can now be computed in an equivalent and consistent way using the corresponding coordinate vectors in ${\rm I\!R}^n$  
- e.g. addition and scalar multiplication of vectors in V correspond to addition and scalar multiplication of their coordinate vectors in ${\rm I\!R}^n$


# Coordinate system

<center><img src="img/vector_2d_add.png" alt="matrix" width="400"/></center>

## Numpy and Vector Algebra

- to represent coordinate vectors: one dimensional Numpy arrays?
- to guarantee consistency with other operations defined later (e.g. inner product) we need to use two dimensional arrays
- coordinate vector can be a *row* vector (e.g. [1  4]) or a *column* vector (e.g. $\begin{bmatrix} 1 \\ 4 \\ \end{bmatrix}$)
- by default: column vector

In [2]:
print('Not like this:')
u = np.array([1,4])
print(u)

print('but rather like this:')
u = np.array([1,4]).reshape(-1,1)
print(u)

Not like this:
[1 4]
but rather like this:
[[1]
 [4]]


In [3]:
u = np.array([1,4]).reshape(-1,1)
v = np.array([5,1]).reshape(-1,1)
u + v

array([[6],
       [5]])

In [4]:
u = np.array([1,4]).reshape(-1,1)
v = np.array([5,1]).reshape(-1,1)
u - v

array([[-4],
       [ 3]])

In [5]:
u = np.array([1,4]).reshape(-1,1)
2 * u

array([[2],
       [8]])

## Numpy and Vector Algebra

- numpy allows operations on multidimensional arrays
- standard arithemtic operators: `{+ - * / ** %}` 
  - if arrays have the same size, then operator is applied *element wise*
  - or else, *broadcast* is applied

## Universal Functions

- numpy offers functions such as sin, cos, exp, etc
- they operate *element-wise* on an array and output an array
  - it is just a convenient way to avoid loops and optimize efficiency

In [6]:
X = np.arange(3).reshape(-1,1)
print(X)
np.exp(X)

[[0]
 [1]
 [2]]


array([[1.        ],
       [2.71828183],
       [7.3890561 ]])

In [7]:
np.sqrt(X)

array([[0.        ],
       [1.        ],
       [1.41421356]])

# WARNING

- there is a *difference* between the element wise operations and the operations of vector algebra
  - element wise sum/subtraction is the same 
  - the notion of product(s) for example is *not*
  - the notion of exponentials or square root is also *not* the same
- this is because operations of vector/matrix algebra are defined to have certain mathematical properties and are not designed for efficient calculation 

# Matrix theory (linear transformations)

- if:
  - $V$ and $W$ are an n-dimensional and m-dimensional vector spaces
  - a basis of $V$ and a basis of $W$ have been fixed
- then any *linear transformation* $T: V → W$ may be encoded by an $m × n$ matrix $A$
- two matrices that encode the *same* linear transformation in different bases are called *similar* 

# Matrix theory

- matrix theory replaces the study of linear transformations
  - which are defined axiomatically
- by the study of matrices
  - which are concrete objects
- one advantage of working on linear transformations via matrices is the possibility to compute useful functions of the representative matrices (e.g. the determinant)

# Matrix

- a matrix is a rectangular array of numbers  (in Numpy parlance, it is a 2-dimensional array)
- the individual numbers are matrix *elements*
- the horizontal and vertical sequences of numbers are called *rows* and *columns*, respectively
- a matrix has a *size* defined by the number of rows and columns

# Matrix

- a matrix with $m$ rows and $n$ columns is called an $m \times n$ matrix or m-by-n matrix
<center><img src="img/mat.png" alt="matrix" width="400"/></center>

# Matrix

- matrices made of a single row (column) are called row (column) vectors
- a matrix with the same number of rows and columns is called a *square* matrix


| Name	| Size | Example |
| --- | --- | --- |
| Row vector | $$1 \times n$$ |\begin{bmatrix}3&7&2\end{bmatrix} |
| Column vector | $$n \times 1$$ |\begin{bmatrix}4\\1\\8\end{bmatrix}|
|Square matrix| $$n \times n$$| \begin{bmatrix}9&13&5\\1&11&7\\2&6&3\end{bmatrix} |


# Operations on matrices

- we can view a matrix as a tuple of vectors stacked together
  - i.e. as many column vectors or as many row vectors 
- the sum between matrices is defined as the sum of the corresponding vectors
- the product between a scalar and a matrix is defined as the product of the scalar for each vector

# Operations on matrices

sum:
$$\begin{bmatrix}1&3&1\\1&0&0\end{bmatrix}+\begin{bmatrix}0&0&5\\7&5&0\end{bmatrix}=\begin{bmatrix}1+0&3+0&1+5\\1+7&0+5&0+0\end{bmatrix}=\begin{bmatrix}1&3&6\\8&5&0\end{bmatrix}$$

scalar product:
$$2\cdot \begin{bmatrix}1&8&-3\\4&-2&5\end{bmatrix}=\begin{bmatrix}2\cdot 1&2\cdot 8&2\cdot -3\\2\cdot 4&2\cdot -2&2\cdot 5\end{bmatrix}=\begin{bmatrix}2&16&-6\\8&-4&10\end{bmatrix}$$

# Operations on matrices

We'll see these operations:

- transposition
- rank
- trace
- determinant

# Transposition

- the transpose of a matrix is an operator which flips a matrix over its diagonal
- i.e. it switches the row and column indices of the matrix 
- the result is a matrix denoted as $A^T$ (also written $A′$, $A^{tr}$ or $A^t$).

In [8]:
A = np.arange(10).reshape(5,2)
print(A)

print

B = A.T
print(B)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


## Note:

To better represent matrices in a Jupyter, use:

In [9]:
from sympy import init_printing 
from sympy import Matrix
init_printing(use_latex=True)
def out(mat, n=2): return Matrix(np.round(mat, decimals=n))

In [ ]:
out(A)

In [ ]:
out(B)

# Rank

- the rank of a matrix $A$ is the dimension of the vector space generated 
<br>(or spanned) by its columns
- it is the maximal number of linearly independent columns of $A$
- i.e. equal to the dimension of the space spanned by its columns

In [10]:
print(np.eye(3))
np.linalg.matrix_rank(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3

In [11]:
A = np.array([[1,2,3], [2,3,4], [1,1,1]]).T 
print(A)
np.linalg.matrix_rank(A)

[[1 2 1]
 [2 3 1]
 [3 4 1]]


2

# Trace

- given a *square* matrix $A$ one can define the *trace* 
<br>as the sum of the elements on the main diagonal of $A$
$${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$$
- where $a_{ii}$ denotes the entry on the $i$th row and $i$th column of A. 

# Properties of $tr$

- it is invariant with respect to a change of basis
- the trace is a linear mapping:
<br>for all square matrices A and B, and all scalars c
$${\displaystyle {\begin{aligned}\operatorname {tr} (A+B)&=\operatorname {tr} (A)+\operatorname {tr} (B)\\\operatorname {tr} (cA)&=c\operatorname {tr} (A)\end{aligned}}}$$

- a matrix and its transpose have the same trace:
$${\displaystyle \operatorname {tr} (A)=\operatorname {tr} \left(A^{\mathrm {T} }\right)}$$

# Determinant

- given a *square* matrix $A$ one can define the *determinant*
<br>denoted $\det(A)$, $\det A$, or $|A|$ 
- it's the volume of the parallelepiped formed by the column vectors

<img src="img/paral.png" alt="det" width="500"/>

# Properties of $\det$

- it is invariant with respect to a change of basis
- a mapping has an *inverse* if and only if the determinant is not zero
- if we write the vectors as the columns (or rows) of a matrix, 
<br>and if the determinant of that matrix is zero, 
<br>then the vectors are linearly dependent

In [12]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

In [13]:
A = np.array([[1, 2], [2, 4]])
np.linalg.det(A)

# Properties of $\det$

- $\det(I_{n})=1$ where $I_n$ is the $n × n$ **identity** matrix.
- $\det(A^{-1})={\frac {1}{\det(A)}}=\det(A)^{-1}$
- for **square** matrices A and B of equal size: $\det(AB)=\det(A)\det(B)$

In [14]:
A = np.eye(3)
print(A)
np.linalg.det(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
A = np.array([[1, 2], [2, 1]])
print(A)
B = np.array([[3, 2], [2, 3]])
print(B)
print('det(A): %.1f'%np.linalg.det(A))
print('det(B): %.1f'%np.linalg.det(B))
print('det(A)*det(B): %.1f  --- det(AB):%.1f'%(np.linalg.det(A)*np.linalg.det(B), np.linalg.det(np.dot(A,B))))

[[1 2]
 [2 1]]
[[3 2]
 [2 3]]
det(A): -3.0
det(B): 5.0
det(A)*det(B): -15.0  --- det(AB):-15.0


# A useful function: `diag`

- Sometime it is useful to extract a diagonal or construct a diagonal array
- blueprint `numpy.diag(v)`
- Note: 
  - if v is a 2-D array, return a copy of its diagonal as a 1-D array
  - if v is a 1-D array, return a 2-D array with v on the diagonal

In [16]:
X = np.arange(9).reshape((3,3))
print(X)
np.diag(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [17]:
v = np.diag(X)
np.diag(v)

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

# Summary


- given basis ${v_1, v_2, ..., v_n}$ of $V$ we can construct a *coordinate* system for $V$: the vector with coordinates $(a_1, a_2, ..., a_n)$ is the linear combination $a_{1}v_{1}+a_{2}v_{2}+\cdots +a_{n}v_{n}$

- if $V$ and $W$ are an n-dimensional and m-dimensional vector spaces, and a basis of $V$ and a basis of $W$ have been fixed, then any linear transformation $T: V → W$ may be encoded by an $m × n$ matrix $A$

- operations over vectors can be equivalently expressed using matrices